// <auto-generated />
using System;
using FeedCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedCraft.Infrastructure.Migrations
{
    [DbContext(typeof(FeedCraftDbContext))]
    [Migration("20260823044428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPerUnit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerUnit = 0.20000000000000001,
                            MaxInclusionPct = 100.0,
                            Name = "Maize"
                        },
                        new
                        {
                            Id = 2,
                            CostPerUnit = 0.34999999999999998,
                            MaxInclusionPct = 100.0,
                            Name = "Soybean Meal"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 0.25,
                            MaxInclusionPct = 100.0,
                            Name = "Mustard Meal"
                        },
                        new
                        {
                            Id = 4,
                            CostPerUnit = 0.90000000000000002,
                            MaxInclusionPct = 100.0,
                            Name = "Vegetable Oil"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("IngredientId", "NutrientDefinitionId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("IngredientNutrientValues", (string)null);

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 1,
                            Value = 8.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 2,
                            Value = 3.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 3,
                            Value = 0.25
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 4,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 5,
                            Value = 3300.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 1,
                            Value = 44.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 2,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 3,
                            Value = 2.7999999999999998
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 4,
                            Value = 6.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 5,
                            Value = 2200.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 1,
                            Value = 35.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 2,
                            Value = 8.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 3,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 4,
                            Value = 7.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 5,
                            Value = 2800.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 2,
                            Value = 100.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 5,
                            Value = 8800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.HasKey("NutrientDefinitionId");

                    b.ToTable("NutrientConstraints", (string)null);

                    b.HasData(
                        new
                        {
                            NutrientDefinitionId = 1,
                            MaxValue = 24.0,
                            MinValue = 20.0
                        },
                        new
                        {
                            NutrientDefinitionId = 2,
                            MaxValue = 10.0,
                            MinValue = 3.0
                        },
                        new
                        {
                            NutrientDefinitionId = 3,
                            MaxValue = 1.5,
                            MinValue = 1.0
                        },
                        new
                        {
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0,
                            MinValue = 0.0
                        },
                        new
                        {
                            NutrientDefinitionId = 5,
                            MaxValue = 3200.0,
                            MinValue = 2800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NutrientDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPercentage = true,
                            Name = "Crude Protein",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 2,
                            IsPercentage = true,
                            Name = "Fat",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            IsPercentage = true,
                            Name = "Lysine",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 4,
                            IsPercentage = true,
                            Name = "Ash",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 5,
                            IsPercentage = false,
                            Name = "ME",
                            Unit = "kcal/kg"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.SavedFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedFormulations", (string)null);
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.Ingredient", null)
                        .WithMany("NutrientValues")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("NutrientValues");
                });
#pragma warning restore 612, 618
        }
    }
}
