// <auto-generated />
using System;
using FeedCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedCraft.Infrastructure.Migrations
{
    [DbContext(typeof(FeedCraftDbContext))]
    [Migration("20260823055549_AddIdentityAndDealerListings")]
    partial class AddIdentityAndDealerListings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FeedCraft.Domain.Models.DealerListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DealerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerUserId");

                    b.HasIndex("IngredientName");

                    b.ToTable("DealerListings", (string)null);
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPerUnit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerUnit = 0.20000000000000001,
                            MaxInclusionPct = 100.0,
                            Name = "Maize"
                        },
                        new
                        {
                            Id = 2,
                            CostPerUnit = 0.34999999999999998,
                            MaxInclusionPct = 100.0,
                            Name = "Soybean Meal"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 0.25,
                            MaxInclusionPct = 100.0,
                            Name = "Mustard Meal"
                        },
                        new
                        {
                            Id = 4,
                            CostPerUnit = 0.90000000000000002,
                            MaxInclusionPct = 100.0,
                            Name = "Vegetable Oil"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("IngredientId", "NutrientDefinitionId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("IngredientNutrientValues", (string)null);

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 1,
                            Value = 8.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 2,
                            Value = 3.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 3,
                            Value = 0.25
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 4,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 5,
                            Value = 3300.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 1,
                            Value = 44.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 2,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 3,
                            Value = 2.7999999999999998
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 4,
                            Value = 6.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 5,
                            Value = 2200.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 1,
                            Value = 35.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 2,
                            Value = 8.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 3,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 4,
                            Value = 7.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 5,
                            Value = 2800.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 2,
                            Value = 100.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 5,
                            Value = 8800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.HasKey("NutrientDefinitionId");

                    b.ToTable("NutrientConstraints", (string)null);

                    b.HasData(
                        new
                        {
                            NutrientDefinitionId = 1,
                            MaxValue = 24.0,
                            MinValue = 20.0
                        },
                        new
                        {
                            NutrientDefinitionId = 2,
                            MaxValue = 10.0,
                            MinValue = 3.0
                        },
                        new
                        {
                            NutrientDefinitionId = 3,
                            MaxValue = 1.5,
                            MinValue = 1.0
                        },
                        new
                        {
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0,
                            MinValue = 0.0
                        },
                        new
                        {
                            NutrientDefinitionId = 5,
                            MaxValue = 3200.0,
                            MinValue = 2800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NutrientDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPercentage = true,
                            Name = "Crude Protein",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 2,
                            IsPercentage = true,
                            Name = "Fat",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            IsPercentage = true,
                            Name = "Lysine",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 4,
                            IsPercentage = true,
                            Name = "Ash",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 5,
                            IsPercentage = false,
                            Name = "ME",
                            Unit = "kcal/kg"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.SavedFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedFormulations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f3c1d2e-7a54-4b18-9c60-2f8e5b1a4d73",
                            ConcurrencyStamp = "0c7d4a91-5e26-49b3-8f11-6ad38c705b42",
                            Name = "Dealer",
                            NormalizedName = "DEALER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.DealerListing", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("DealerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.Ingredient", null)
                        .WithMany("NutrientValues")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("NutrientValues");
                });
#pragma warning restore 612, 618
        }
    }
}
