// <auto-generated />
using System;
using FeedCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedCraft.Infrastructure.Migrations
{
    [DbContext(typeof(FeedCraftDbContext))]
    [Migration("20260823065856_AddKnowledgeBase")]
    partial class AddKnowledgeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FeedCraft.Domain.Models.DealerListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DealerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerUserId");

                    b.HasIndex("IngredientName");

                    b.ToTable("DealerListings", (string)null);
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPerUnit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinInclusionPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerUnit = 0.20000000000000001,
                            MaxInclusionPct = 100.0,
                            Name = "Maize"
                        },
                        new
                        {
                            Id = 2,
                            CostPerUnit = 0.34999999999999998,
                            MaxInclusionPct = 100.0,
                            Name = "Soybean Meal"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 0.25,
                            MaxInclusionPct = 100.0,
                            Name = "Mustard Meal"
                        },
                        new
                        {
                            Id = 4,
                            CostPerUnit = 0.90000000000000002,
                            MaxInclusionPct = 100.0,
                            Name = "Vegetable Oil"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("IngredientId", "NutrientDefinitionId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("IngredientNutrientValues", (string)null);

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 1,
                            Value = 8.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 2,
                            Value = 3.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 3,
                            Value = 0.25
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 4,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 1,
                            NutrientDefinitionId = 5,
                            Value = 3300.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 1,
                            Value = 44.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 2,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 3,
                            Value = 2.7999999999999998
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 4,
                            Value = 6.0
                        },
                        new
                        {
                            IngredientId = 2,
                            NutrientDefinitionId = 5,
                            Value = 2200.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 1,
                            Value = 35.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 2,
                            Value = 8.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 3,
                            Value = 1.5
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 4,
                            Value = 7.0
                        },
                        new
                        {
                            IngredientId = 3,
                            NutrientDefinitionId = 5,
                            Value = 2800.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 2,
                            Value = 100.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            IngredientId = 4,
                            NutrientDefinitionId = 5,
                            Value = 8800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.KnowledgeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalType");

                    b.ToTable("KnowledgeEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Broiler",
                            Content = "The starter phase covers hatch to roughly ten days of age, when the chick's growth rate relative to its own body weight is the highest it will ever be. Feed intake is still small, so every gram has to be nutrient-dense: the specification is driven by amino acid concentration rather than by energy.\n\nPublished targets for this phase sit at 22-24% crude protein and 2,950-3,050 kcal/kg metabolisable energy, with digestible lysine at 1.25-1.45%. The protein-to-energy ratio matters more than either figure on its own - diluting protein while holding energy produces fatty birds with poor early frame development.\n\nStarter feed is normally offered as a crumb. Physical form is not something this tool models, but it affects intake enough that a least-cost mix which looks correct on paper can still underperform if it is fed as a coarse mash.",
                            Stage = "Starter (0-10 days)",
                            Title = "Broiler Starter (0-10 days)"
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Broiler",
                            Content = "From about eleven to twenty-four days the bird is still growing quickly but is now eating enough that nutrient density can be relaxed slightly. Crude protein steps down to 20-22% while energy steps up to 3,000-3,100 kcal/kg.\n\nDigestible lysine of 1.10-1.25% remains the amino acid that limits growth, and the other essential amino acids are usually specified as a ratio to it - methionine plus cystine at about 75% of lysine, threonine at about 65%. This application tracks whichever nutrients you define, so those ratios can be added as extra nutrient rows on the formulation page if you want to formulate against them directly.\n\nFat is given a wider band here (4-9%) because supplemental oil is the cheapest way to lift energy once the grain fraction is already near its practical maximum.",
                            Stage = "Grower (11-24 days)",
                            Title = "Broiler Grower (11-24 days)"
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Broiler",
                            Content = "The finisher phase runs from around twenty-five days to slaughter. Growth is slowing, feed conversion is what drives profit, and the ration shifts decisively towards energy: 3,050-3,200 kcal/kg against a reduced 18-20% crude protein.\n\nDigestible lysine falls to 0.95-1.10%. This is also the phase where withdrawal requirements apply - any additive carrying a mandated clearance period has to be out of the feed before the birds are processed.\n\nBecause energy rather than protein is the binding requirement here, the finisher is the ration whose least-cost answer is most sensitive to the oil price. That makes it a useful example when discussing marginal values: a small change in the cost of the energy source moves the entire solution.",
                            Stage = "Finisher (25 days to market)",
                            Title = "Broiler Finisher (25 days to market)"
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Layer",
                            Content = "A commercial layer at peak production - roughly 26 to 45 weeks - converts feed into an egg on almost every day of the period. The ration is built around a steady daily nutrient intake rather than around growth, so commercial specifications are usually quoted per hen per day as well as per kilogram of feed.\n\nPublished targets are 16-18% crude protein, 2,750-2,900 kcal/kg metabolisable energy and 0.80-0.95% digestible lysine. Energy is deliberately held lower than in any broiler ration: a hen eats to her energy requirement, so an over-dense feed reduces intake enough to leave her short of protein and calcium.\n\nCalcium is what really distinguishes a layer ration from every other feed described here. A hen in lay needs 3.5-4.2% dietary calcium, most of it from a coarse particulate source such as limestone or oyster shell so that it dissolves slowly overnight while the shell is being formed. The four ingredients seeded in this application supply almost none, so a limestone or dicalcium phosphate row has to be added to the ingredient library before a genuine layer ration can be formulated.\n\nThe ash ceiling in the table below is set at 14% rather than the 8% used for broilers precisely because a real layer ration carries that mineral load.",
                            Stage = "Peak production (26-45 weeks)",
                            Title = "Layer, Peak Production"
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "Cattle",
                            Content = "This entry covers the concentrate portion of a lactating dairy cow's diet, not the total ration. A cow in milk takes most of her dry matter as forage; the concentrate is the fraction formulated to close the gap between what that forage supplies and what production requires. The figures below are therefore not comparable with the poultry entries above.\n\nTypical targets for a dairy concentrate are 16-18% crude protein and 2,600-2,800 kcal/kg metabolisable energy, with fat held to 2-6%. That fat ceiling is a rumen constraint rather than a nutritional one: above roughly 6-7% total dietary fat, unprotected oil begins to inhibit fibre-digesting bacteria and depresses both intake and milk fat percentage.\n\nNo lysine target is listed, and the omission is deliberate. Rumen microbes synthesise amino acids from degradable nitrogen, so the amino acid profile of the feed itself is a poor predictor of what the cow actually absorbs. Constraining a ruminant concentrate to a dietary lysine minimum the way you would for a broiler is not meaningful. Loading this template consequently clears the lysine bounds on the formulation form rather than setting them.\n\nEffective fibre matters as much as any number in the table, and this tool does not model it. A concentrate that meets every target below can still cause rumen acidosis if it is fed without adequate long forage.",
                            Stage = "Lactating concentrate",
                            Title = "Dairy Cattle, Lactating Concentrate"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.KnowledgeEntryTarget", b =>
                {
                    b.Property<int>("KnowledgeEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("KnowledgeEntryId", "NutrientDefinitionId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("KnowledgeEntryTargets", (string)null);

                    b.HasData(
                        new
                        {
                            KnowledgeEntryId = 1,
                            NutrientDefinitionId = 1,
                            MaxValue = 24.0,
                            MinValue = 22.0
                        },
                        new
                        {
                            KnowledgeEntryId = 1,
                            NutrientDefinitionId = 2,
                            MaxValue = 8.0,
                            MinValue = 3.0
                        },
                        new
                        {
                            KnowledgeEntryId = 1,
                            NutrientDefinitionId = 3,
                            MaxValue = 1.45,
                            MinValue = 1.25
                        },
                        new
                        {
                            KnowledgeEntryId = 1,
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0
                        },
                        new
                        {
                            KnowledgeEntryId = 1,
                            NutrientDefinitionId = 5,
                            MaxValue = 3050.0,
                            MinValue = 2950.0
                        },
                        new
                        {
                            KnowledgeEntryId = 2,
                            NutrientDefinitionId = 1,
                            MaxValue = 22.0,
                            MinValue = 20.0
                        },
                        new
                        {
                            KnowledgeEntryId = 2,
                            NutrientDefinitionId = 2,
                            MaxValue = 9.0,
                            MinValue = 4.0
                        },
                        new
                        {
                            KnowledgeEntryId = 2,
                            NutrientDefinitionId = 3,
                            MaxValue = 1.25,
                            MinValue = 1.1000000000000001
                        },
                        new
                        {
                            KnowledgeEntryId = 2,
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0
                        },
                        new
                        {
                            KnowledgeEntryId = 2,
                            NutrientDefinitionId = 5,
                            MaxValue = 3100.0,
                            MinValue = 3000.0
                        },
                        new
                        {
                            KnowledgeEntryId = 3,
                            NutrientDefinitionId = 1,
                            MaxValue = 20.0,
                            MinValue = 18.0
                        },
                        new
                        {
                            KnowledgeEntryId = 3,
                            NutrientDefinitionId = 2,
                            MaxValue = 10.0,
                            MinValue = 4.0
                        },
                        new
                        {
                            KnowledgeEntryId = 3,
                            NutrientDefinitionId = 3,
                            MaxValue = 1.1000000000000001,
                            MinValue = 0.94999999999999996
                        },
                        new
                        {
                            KnowledgeEntryId = 3,
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0
                        },
                        new
                        {
                            KnowledgeEntryId = 3,
                            NutrientDefinitionId = 5,
                            MaxValue = 3200.0,
                            MinValue = 3050.0
                        },
                        new
                        {
                            KnowledgeEntryId = 4,
                            NutrientDefinitionId = 1,
                            MaxValue = 18.0,
                            MinValue = 16.0
                        },
                        new
                        {
                            KnowledgeEntryId = 4,
                            NutrientDefinitionId = 2,
                            MaxValue = 8.0,
                            MinValue = 3.0
                        },
                        new
                        {
                            KnowledgeEntryId = 4,
                            NutrientDefinitionId = 3,
                            MaxValue = 0.94999999999999996,
                            MinValue = 0.80000000000000004
                        },
                        new
                        {
                            KnowledgeEntryId = 4,
                            NutrientDefinitionId = 4,
                            MaxValue = 14.0
                        },
                        new
                        {
                            KnowledgeEntryId = 4,
                            NutrientDefinitionId = 5,
                            MinValue = 2750.0,
                            Note = "No upper bound is loaded: the four seeded ingredients cannot fall below about 3,005 kcal/kg at this protein level. Add a fibrous ingredient such as rice bran or wheat bran to reach the published window."
                        },
                        new
                        {
                            KnowledgeEntryId = 5,
                            NutrientDefinitionId = 1,
                            MaxValue = 18.0,
                            MinValue = 16.0
                        },
                        new
                        {
                            KnowledgeEntryId = 5,
                            NutrientDefinitionId = 2,
                            MaxValue = 6.0,
                            MinValue = 2.0
                        },
                        new
                        {
                            KnowledgeEntryId = 5,
                            NutrientDefinitionId = 4,
                            MaxValue = 10.0
                        },
                        new
                        {
                            KnowledgeEntryId = 5,
                            NutrientDefinitionId = 5,
                            MinValue = 2600.0,
                            Note = "No upper bound is loaded: the four seeded ingredients cannot fall below about 3,005 kcal/kg at this protein level. Add a fibrous ingredient such as rice bran or wheat bran to reach the published window."
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.HasKey("NutrientDefinitionId");

                    b.ToTable("NutrientConstraints", (string)null);

                    b.HasData(
                        new
                        {
                            NutrientDefinitionId = 1,
                            MaxValue = 24.0,
                            MinValue = 20.0
                        },
                        new
                        {
                            NutrientDefinitionId = 2,
                            MaxValue = 10.0,
                            MinValue = 3.0
                        },
                        new
                        {
                            NutrientDefinitionId = 3,
                            MaxValue = 1.5,
                            MinValue = 1.0
                        },
                        new
                        {
                            NutrientDefinitionId = 4,
                            MaxValue = 8.0,
                            MinValue = 0.0
                        },
                        new
                        {
                            NutrientDefinitionId = 5,
                            MaxValue = 3200.0,
                            MinValue = 2800.0
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NutrientDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPercentage = true,
                            Name = "Crude Protein",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 2,
                            IsPercentage = true,
                            Name = "Fat",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            IsPercentage = true,
                            Name = "Lysine",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 4,
                            IsPercentage = true,
                            Name = "Ash",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 5,
                            IsPercentage = false,
                            Name = "ME",
                            Unit = "kcal/kg"
                        });
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.SavedFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedFormulations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f3c1d2e-7a54-4b18-9c60-2f8e5b1a4d73",
                            ConcurrencyStamp = "0c7d4a91-5e26-49b3-8f11-6ad38c705b42",
                            Name = "Dealer",
                            NormalizedName = "DEALER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.DealerListing", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("DealerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.IngredientNutrientValue", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.Ingredient", null)
                        .WithMany("NutrientValues")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.KnowledgeEntryTarget", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.KnowledgeEntry", null)
                        .WithMany("Targets")
                        .HasForeignKey("KnowledgeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.NutrientConstraint", b =>
                {
                    b.HasOne("FeedCraft.Domain.Models.NutrientDefinition", null)
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("NutrientValues");
                });

            modelBuilder.Entity("FeedCraft.Domain.Models.KnowledgeEntry", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
